osx_image: xcode9.2
language: objective-c
xcode_project: MultiPeer.xcodeproj

install:
  - wget --output-document /tmp/SwiftLint.pkg https://github.com/realm/SwiftLint/releases/download/0.24.2/SwiftLint.pkg && sudo installer -pkg /tmp/SwiftLint.pkg -target /

script:
  - swiftlint
  - swift build
  - pod spec lint